import "~/styles/globals.css";

import { ClerkProvider } from '@clerk/nextjs'

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import TopNav from "src/app/_components/topnav";

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by Roman",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
      <body>
        <TopNav />
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
